services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
    ports:
      - "8000:8000"
    command: python3 -m service --host=0.0.0.0

  app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile_web
    depends_on:
      - bot
    ports:
      - "5000:5000"
    command: python3 -m flask run --host=0.0.0.0