version: "3"
services:
  bot:
    container_name: bot
    build:
      context: bot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python3 -m service --host=0.0.0.0

  app:
    container_name: flask_app
    build:
      context: web
      dockerfile: Dockerfile
    depends_on:
      - bot
    ports:
      - "5000:5000"
    command: python3 -m flask run --host=0.0.0.0